FROM growerp/flutter-sdk-image:3.22.2 AS base

COPY --chmod=0777 . .

RUN flutter pub get
RUN flutter build apk --split-per-abi

FROM scratch AS export
COPY --from=base ./home/mobiledevops/app/build/app/outputs ./build/android