FROM growerp/flutter-sdk-image:3.22.2 AS build

COPY --chmod=0777 . .

WORKDIR ./apps/desktop

RUN flutter pub get
RUN flutter build web

FROM nginx as serve
COPY --from=build --chmod=0777 /home/mobiledevops/app/apps/desktop/build/web /usr/share/nginx/html