name: todo
description: "A new Flutter package project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_blue_plus: ^1.32.1
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  intl: any

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
